### ISSUE TITLE
All matching characters not marked

### ISSUE THREAD

**Issue by jpmossin** [johnlindquist/AceJump#101]
After upgrading to version 3, I often find that all matching positions are not marked when searching.
As an example, consider line 23 in the attached image, where I am searching for "a": Both "AceJumpAction" and "DumpAwareAction" have "a"s that are not marked (but also some that are) and available for navigation. Several other examples can be found in the same image. 

I can't see any reason why these characters should not be marked, so I assume it is a bug?

![acejump_fail](https://cloud.githubusercontent.com/assets/579492/20032460/a5c92b22-a38a-11e6-8ecd-ae27cc8aee3a.png)

**Comment by breandan** [comment]
@jpmossin, thank you for trying AceJump 3.0 and submitting your feedback! As mentioned in this issue https://github.com/johnlindquist/AceJump/issues/79#issuecomment-255903394, we are currently tagging one result per word only. This is to avoid tagging "eee" three times. Although we could try to implement a heuristic where, if the results are a certain spacing apart inside a word, we should tag every one. Do you think it is absolutely important to tag every letter inside a word on the first keystroke? Anyone else who sees this issue, feel free to chime in as well.

PS. If you need to reach another result inside the word, you can keep typing the next [n] source characters, and one of them should disambiguate.

PPS. Your tags look weird in the screenshot. Are you using any custom font settings?

**Comment by jpmossin** [comment]
Thank you for the reply. That explains the issue, and I understand your reasoning, but yes: I must say that jumping to an exact location in the fastest possible way was the key functionality in AceJump for me.

I am sure the new version brings many improvements, but after having used AceJump every day for years now this feels a bit more like a new plugin than an upgrade (the dynamic positioning of the indicators is an example of this, consider for example line 23 and "AceJumpAction", I really have to think 2 seconds to figure out which label is connected to where). Would you consider either releasing the v2 as a separate plugin or making it compatible with 2016.2 and newer (the buildUntil parameter in v2.0.7 is set to 145.9999). I could not find any license info in the repo, but I would be happy to try to maintain a v2 fork myself if that would be ok with you. 

ps. I am not using any custom font that I am aware of, running on Ubuntu 16.04.

**Comment by breandan** [comment]
I completely understand where you're coming from - there are a few inconsistencies with the behavior of AceJump 2.0 (namely the placement of tags and the tagging of multiple results per word), which may be uncomfortable to longtime users of AceJump. I am confident we can solve both of these issues in AceJump 3.0 with minor tweaks, as I would like to support everyone's use case. However, if you feel this is an unacceptable change, the JetBrains plugin repository hosts an archive of every version, including the [last stable version](https://plugins.jetbrains.com/update/index?pr=idea&updateId=27197) of AceJump 2.

Here are my ideas for addressing the issues you mentioned:

* It should be possible to visually emphasize which tags are connected to which characters. Possibly a border effect, or anchoring the moving tags when typing. I agree there are graphical improvements that can be made. However, it should be noted that this was also an issue in AceJump 2 if the tags were very crowded (ie. try typing spacebar with the old AceJump and you'll see what I mean).

* Add a heuristic for tagging nearby letters inside a word. We won't tag two adjacent letters, but it might be possible to tag every other matching one, or only those with a small gap (say two or three characters). Do you this is an acceptable compromise? Just curious if you have tried continuing to type inside a word (ie. if you want to jump to "An[A]ctionEvent", just type "ac", then the jump target). You might like it!

PS. That's odd, I'm using Ubuntu 16.04 too. Did the tag font look so tiny prior to updating?
