### ISSUE TITLE
Could you add 'end of line' feature?

### ISSUE THREAD

**Issue by Jaynarol** [johnlindquist/AceJump#102]
Could you add 'end of line' feature?

like as [ctrl+; and tab] = [go to end of current line]

thank you for great plugins ;)

**Comment by breandan** [comment]
Sure! End of lines can be reached already via <kbd>Ctrl</kbd>+<kbd>;</kbd>,<kbd>→</kbd> or <kbd>End</kbd>. If you are looking for customizable shortcut keys, please follow #84. Thanks!
