### ISSUE TITLE
Allow line mode shortcuts remapping

### ISSUE THREAD

**Issue by h0tk3y** [johnlindquist/AceJump#105]
When navigating without arrow keys, it's quite inconvenient to use the arrow keys for line mode triggering.

Either of these would be good:

* an option to remap line mode keys 
* use `Left`, `Right` and `Up` IDEA actions for triggering line mode (so that I can use my keys assigned to these actions)
* add separate actions for jump in line mode (without the need to switch to line mode, i.e. an action per each of the modes)

**Comment by breandan** [comment]
Just added an secondary action to trigger line mode (bound to <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>;</kbd> by default) that tags the beginning, line indents and end of line positions.
