### ISSUE TITLE
[Suggestion] Default keybinding for Line mode

### ISSUE THREAD

**Issue by mallowigi** [johnlindquist/AceJump#108]
IMO the default binding for line mode should be Ctrl+Shift+G, similarly to Ctrl+G (Go to line)

**Comment by breandan** [comment]
Thanks for your feedback. <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>G</kbd> is currently the default binding for "Unselect Occurrence" on Mac OS X, as well as several other keymaps in IntelliJ IDEA. Are there any objections to overwriting this action?
