### ISSUE TITLE
Target Mode doesn't work

### ISSUE THREAD

**Issue by rafaelcapucho** [johnlindquist/AceJump#109]
Hi,

When I press `Ctrl+;` it starts AceJump and I'm able to use it properly.. but I'm unable to enter in target mode if a press it twice or press a `;` after the `Ctrl+;` as described.

Version: 3.0.7 - PyCharm 2016.2.3 - ArchLinux

Thank you.

**Comment by breandan** [comment]
To activate *Target Mode*, you must to fully press <kbd>Ctrl</kbd>+<kbd>;</kbd> twice, or press and hold <kbd>Ctrl</kbd>, then press <kbd>;</kbd> twice. Alternatively, if you are on [AceJump 3.1.5](https://plugins.jetbrains.com/plugin/download?pr=idea&updateId=31535), we now support entering *Target Mode* directly by pressing the shortcut key bound to `AceTargetMode` (<kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>;</kbd> by default). I have updated [the instructions](https://github.com/johnlindquist/AceJump#acejump) to reflect this change.
