### ISSUE TITLE
Request: Support AltGr with Alt for immediate selection

### ISSUE THREAD

**Issue by suamikim** [johnlindquist/AceJump#11]
Hy there,

I think it would be nice if you could support the AltGr key together with the Alt key to immediately select the word at the jump target.

If e.g. I jump to a place with the C key it'd be more convenient to do this by pressing AltGr + C than Alt + C because I could use both hands instead of one...

Thanks & best regards

**Comment by breandan** [comment]
Not sure what this refers to, possibly an old behavior. The <kbd>Alt</kbd> key is no longer part of the AceJump UI. Feel free to give [AceJump 3.0 Beta](https://github.com/johnlindquist/AceJump/releases/tag/3.0.0) a try and report any issues you may encounter. Feedback welcome! Thanks
