### ISSUE TITLE
Acejump Ctrl+; does not work on Mac UNFOLLOW

### ISSUE THREAD

**Issue by Fred-J** [johnlindquist/AceJump#119]
AceJump 3.1.6 is installed in Webstorm 11.0.4 on Mac El Capitan

Hitting Ctrl+; and then typing a character, failed to hight light the matching characters. 

How can I get AceJump to work?

**Comment by breandan** [comment]
I am unable to reproduce the problem as described. Have you rebound the default AceJump shortcut (check **Settings | Keymap | AceJump**)? Are there any errors displayed?

**Comment by BoWuGit** [comment]
still not work with 3.2.0, win 10, newest jetbrains ide. It's no use rebounding, and nothing errors display.
"ctrl+ shift+ ;" works, and "ctrl + ;" seldom work.
Thanks for your care.

**Comment by shijiebei2009** [comment]
doesn't work in idea 2016.2 either，noting message display when press ctrl+;

**Comment by Fred-J** [comment]
Fixed after updating web storm to 2017.1, I remember the keymap shortcut was ^; but now it is Ctrl+;
