### ISSUE TITLE
Jump to non-ambiguous hits right away

### ISSUE THREAD

**Issue by holgerbrandl** [johnlindquist/AceJump#120]
It would be great if AceJump could jump to non-ambigous hits directly. Example
```r

## save the graph data for later
save(graphData, file=".graphData.RData")


orthoGraph = graph.data.frame(graphData, directed=TRUE)
orthoGraphClusters = clusters(orthoGraph)

orthoGraphClusters$membership, sep="_"))
orthoGroups = data_frame(contig=V(orthoGraph)$name) %>%
    inner_join(vec_as_df(orthoGraphClusters$membership, "contig", "ortho_group"))

write_tsv(orthoGroups, path="orthoGroups.txt")
```
Ctrl-; --> wr --> why waiting for another "A" if there is just a single hit anyway? So move the goddamn cursor right away. :-)

**Comment by breandan** [comment]
This was actually implemented in a previous version, but it caused a usability problem. If AceJump jumps to a target prior to the user completing the tag, it can insert a letter in the editor, or replace a selection. It is difficult for users to anticipate when a tag will become unambiguous, so they will often type the remaining characters in a tag, producing unexpected text if you are typing quickly.

I'm going to mark this as "Won't fix", but thanks for the suggestion!

**Comment by breandan** [comment]
I'm going ahead with this, but with the <kbd>Enter</kbd> key to indicate deliberate selection. Please follow #146 for updates. Thanks!
