### ISSUE TITLE
Add hotkey to jump to next character.

### ISSUE THREAD

**Issue by mmagyar** [johnlindquist/AceJump#133]
Add a hotkey that jumps to the next instance of a given single character, similar to `f` in VIM, without additional input.

I think others would also find this useful, since i noticed that 80 percent of the time, i just want to jump to the next comma or colon or parentheses.

It could have a default key combination of ctrl + super + ;

**Comment by breandan** [comment]
Doesn't `/` + `<character>` + `Enter` in IdeaVim, or `Ctrl`+`F` + `<character>` + `Enter` in IntelliJ IDEA already do this?

**Comment by mmagyar** [comment]
In IdeaVim `f` + `<character>` works. I'd like to have something as close to that as possible, outside of vim mode.

in normal input mode, `Ctrl` + `F` + `<character>` + `Esc` kinda sorta does this, but it's not ideal, since by default it remembers the last search, it adds lots of visual noise by highlighting all the matches, which is not something i would want, plus it is one additional keystroke.
