### ISSUE TITLE
Is there a way to map AceJump to act on keychords?

### ISSUE THREAD

**Issue by xelibrion** [johnlindquist/AceJump#137]
I have ace-jump setup in Emacs to be triggered by `jj`/`jk` keychords, is there a way to achieve something like that in IntelliJ given I'm not using `vim` keyboard layout (using Emacs keymap instead).

**Comment by breandan** [comment]
Have you tried [emacsIDEAs](https://github.com/whunmr/emacsIDEAs)? It's a different plugin, but has a similar interface. @whunmr

**Comment by breandan** [comment]
I'm going to say this is not possible right now, but may be something worth investigating in the future. There is no proper Emacs emulation for the IntelliJ Platform, so this would depend on a plugin that supported Emacs key customization. Implementing this from scratch is probably out of scope for the AceJump project.
