### ISSUE TITLE
On running Activate AceJump Mode text cursor freezes. Not possible to type or switch mode (command/insert). Need to reload Webstorm

### ISSUE THREAD

**Issue by SvitlanaShepitsena** [johnlindquist/AceJump#141]
Got next notification:
![image](https://cloud.githubusercontent.com/assets/5209402/26647327/a03b5b0e-4604-11e7-9e19-9c0db974a427.png)

**Comment by breandan** [comment]
This error should now be fixed in the [latest update](https://plugins.jetbrains.com/plugin/7086-acejump/update/35584). Please feel free to reopen #138 if the issue persists. Thanks for reporting!

**Comment by SvitlanaShepitsena** [comment]
Great! It works on 3.2.3, thank you!!! :-)
