### ISSUE TITLE
ideavim MacOSX Sierra : block selection after jump

### ISSUE THREAD

**Issue by budi** [johnlindquist/AceJump#142]
![jump selection](https://media.giphy.com/media/l0IyfTDsneLOytNao/giphy.gif)

Rather than just moving the cursor to the jump target, AceJump do a block selection from the initial position up to the jump target.

Referring to the image above:
- Cursor at grey
- Trigger AceJump search (blue)
- Pick selection from target (yellow)
- Block selection was made from the previous position up to yellow

```
IntelliJ IDEA 2017.1.3
Build #IU-171.4424.56, built on May 12, 2017
JRE: 1.8.0_112-release-736-b21 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5
ideaVim 0.48
```

**Comment by budi** [comment]
![CE](https://media.giphy.com/media/3ohzdUnn6KIA8I83io/giphy.gif)

Same thing also happens in CE

```
IntelliJ IDEA 2017.1.3
Build #IC-171.4424.56, built on May 13, 2017
JRE: 1.8.0_112-release-736-b21 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5
ideaVim 0.48
```

**Comment by breandan** [comment]
Are you typing <kbd>Shift</kbd> when completing the jump? If so, this is the intended behavior. Capital letters in tags are meant to be selected as lowercase (something we could clarify if this is a common misconception).

**Comment by breandan** [comment]
To clarify, AceJump is completely case-insensitive, as we use <kbd>Shift</kbd> as a control character to indicate "Select from the current position to the desired tag".

**Comment by budi** [comment]
I don't know if it's common, but this sure made me feel embarrassed 😆

**Comment by breandan** [comment]
No worries, it's a little confusing. I'll add a note to the docs. :)

**Comment by budi** [comment]
👍 Thanks!

**Comment by contentfree** [comment]
It'd be nice if the characters were lowercase and then changed to uppercase when shift is pushed to indicate a change in behavior.
