### ISSUE TITLE
3.2.6 does not work with forward, back, up, down

### ISSUE THREAD

**Issue by zurie** [johnlindquist/AceJump#155]
on 3.2.4 I was able to invoke AceJump and then press the left arrow, right arrow, up or down arrow.  Now they no longer correctly work ( right arrow works, but up down left no longer correctly work.  downgrading to 3.2.4 fixes it, upgrading to 3.2.6 breaks it.  

Mac Os X retain 13 / PHPStorm latest (2017.1.4?)   and tested on desktop mac as well.  both work on 3.2.4 both break on 3.2.6  (i share the same keymap and settings for each. not sure if thats related).

**Comment by breandan** [comment]
Thanks for reporting. Should have a fix up shortly.

**Comment by szarouski** [comment]
@zurie just curious, how one can downgrade to older version of plugin?

**Comment by zurie** [comment]
@szarouski you goto https://plugins.jetbrains.com/plugin/7086-acejump

download 3.2.4, then in Phpstorm/Webstorm/etc you just uninstall the plugin.  restart your app and then reinstall the plugin "from disk" and just select the 3.2.4 zip that you grabbed from the URL above.

**Comment by breandan** [comment]
Should be fixed in the latest release. Please let us know if you encounter any issues.
