### ISSUE TITLE
AceJump lagging on large files

### ISSUE THREAD

**Issue by breandan** [johnlindquist/AceJump#161]
Tagging when there are many results or on large files is terribly slow. We need to speed up the tagging process.

**Comment by breandan** [comment]
Related to #33.

**Comment by breandan** [comment]
Just a quick explanation why this occurs. In a recent update, we started scanning the whole document when a user types a string, to support full text search (try it! activate AceJump and type a string on or off the screen, then press <kbd>Tab</kbd> to skip to the next occurrence). However the overhead this operation incurs is quite high. We need to find a way to do this scanning more efficiently.

**Comment by psafarov** [comment]
@breandan Can we add setting allowing to disable full document search? For some users, including me, speed is more important than this feature.

**Comment by breandan** [comment]
I am pretty confident we can get the full text search down to an acceptable latency, as the way we doing it right now is very dumb. Prioritizing this issue going forward. Please let me know if it does not improve in the next few versions and I will implement a toggle switch in the settings.

**Comment by pix2D** [comment]
Just updated to 3.4.0 and performance is absolutely terrible in a 2.5k loc file. Takes 3-5 seconds to process on typing. +1 on having an option to turn this off.

**Comment by psafarov** [comment]
FYI, Acejump-Lite is good as a temporary alternative. It has less features, but it's fast and it works for multiple viewports.

**Comment by pkt-zer0** [comment]
Seems like AceJump-Lite is only for IDEA, not the smaller/cheaper IDEs.

**Comment by helmus** [comment]
Just wanted to point out that switching to the older version doesn't really work because it's difficult not to update extensions automatically to the latest version. Would really appreciate a fix. I used this plugin for the longest time and it really is simply broken now.

**Comment by helmus** [comment]
15$ for the person who fixes this !

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=46543096)](https://www.bountysource.com/issues/46543096-acejump-lagging-on-large-files?utm_source=46543096&utm_medium=shield&utm_campaign=ISSUE_BADGE)
https://www.bountysource.com/issues/46543096-acejump-lagging-on-large-files

**Comment by helmus** [comment]
Any update on this ? I think I would even prefer to just have the full page searching disabled all together over a feature toggle.

**Comment by pkt-zer0** [comment]
Tried reverting to 3.2.7, and 2.0.13 - neither functions correctly anymore with newer IDEs. However, meanwhile there has been a version of [AceJump-Lite](https://plugins.jetbrains.com/plugin/9803-acejump-lite#comment=26217) which works with all IDEs, not just IntelliJ, so I switched to that. Works just fine, pretty much the same way as older versions did.

**Comment by breandan** [comment]
AceJump `3.4.3` ships a number of latency improvements. We also received a nice fix in #214, please consider awarding the bounty to @svensp once it is released.

**Comment by helmus** [comment]
Tried 3.4.3 and the latency is still about 2 seconds ( 300 line files ), completely unusable from a usability perspective.
Excited to see https://github.com/johnlindquist/AceJump/pull/214 released.

**Comment by breandan** [comment]
AceJump `3.5.0` introduces **Word Mode**, a new zero-latency feature for jumping to any word on the screen in two characters or less. It has no default keyboard shortcut, but you can assign one via **Settings | Keymap | 🔍 "AceJump"* | Start in Word Mode*. AceJump `3.5.0` is now available on the plugin repository.
