### ISSUE TITLE
When searching for the line end, need to type tag twice.

### ISSUE THREAD

**Issue by saroff** [johnlindquist/AceJump#164]
1. Use standart AceJump shortcut `ctrl+;` by default.
2. Press right arrow to search for line end.
3. Type tag of desired line. `ED` for example.
4. Then i can see all other line-end tags disappears, but instead appears tags for occurences of `ED` combination.
5. Type desired tag one more time to actually go to line end.

So after typing line-end tag, if this tag can be found in the editor (Like tag is `ED` and there is word `Editor` in the code), then all occurences of it also highlighted with tags. Then i need to type tag once more.

**Comment by breandan** [comment]
Thanks for reporting. I can reproduce and will fix this in the next release.
