### ISSUE TITLE
NoSuchMethodError: com.intellij.openapi.editor.ScrollingModel.scroll(II)V

### ISSUE THREAD

**Issue by Khande** [johnlindquist/AceJump#182]
Platform:
In Android Studio 2.3.3 macOS 10.11.5 
Plugin version: 3.4.0

Error message:
Plugin Error: AceJump threw an uncaught NoSuchMethodError. Disable Plugin
NoSuchMethodError: com.intellij.openapi.editor.ScrollingModel.scroll(II)V

thx.

**Comment by breandan** [comment]
Thanks for reporting!

**Comment by MinRam** [comment]
How to deal with it?  I had to restart my IDE to reset the plugin of AcdJump. could you tell me how to find the way solute this.

**Comment by breandan** [comment]
If you update AceJump, this should be fixed in the latest version.
