### ISSUE TITLE
Regarding support for all word annotations

### ISSUE THREAD

**Issue by Khalian** [johnlindquist/AceJump#184]
Hi

Could there be support for ALL word annotation like easymotion-bd for easymotion vim plugin.

If so, what files would need to be changed for the same?f

**Comment by breandan** [comment]
It will be mapped to <kbd>Space</kbd> in the next release. Thanks for the suggestion!

**Comment by Khalian** [comment]
Is this all words or just the ones we wish to highlight?

**Comment by breandan** [comment]
All words. This is the regex I ended up using: `(?<=[^a-zA-Z0-9_])[a-zA-Z0-9_]`. Did you have something else in mind?
