### ISSUE TITLE
Updated and now slow.

### ISSUE THREAD

**Issue by JamesVannordstrand** [johnlindquist/AceJump#186]
Before I updated AceJump it was working pretty well (a little slow but workable). I just updated today now every time I jump to a character it takes about .5 seconds to display the input characters. This gets pretty annoying if used a lot. Not sure if any contributors classify this as an issue?

**Comment by breandan** [comment]
This is a known issue #161. Fixing this is my main priority. If you need an immediate solution, feel free to roll back to an earlier version on the plugin repository.
