### ISSUE TITLE
Revert to old version until the command backs working consistently.

### ISSUE THREAD

**Issue by wilkerlucio** [johnlindquist/AceJump#193]
Hello, I'm opening this as a gateway for people struggling with the recent issues with AceJump. I love the plugin, but it got unusable recently, it works when the IntelliJ launches but easily stops working, and a restart is required to get it back (see #188 #187 #185 #181 #178 #177 and #175).

Does someone how a version without this issue that we can rollback to? And how to do that? I'm going to try figure by myself, but if someone else already knows that, please share with us.

@breandan, I'm not sure if got that fixed but don't release yet. Can you tell us more about it? By the issues around it, I guess a lot of people are being affected by this one. And please close this once it gets solved.

Thanks.

**Comment by breandan** [comment]
You can download older versions of the plugin on the [plugin repository](https://plugins.jetbrains.com/plugin/7086-acejump) and install them from disk [like so](https://www.jetbrains.com/help/idea/installing-a-plugin-from-the-disk.html). Others have [mentioned](https://github.com/johnlindquist/AceJump/issues/191) `3.3.2` seems to be more stable. Thanks!

**Comment by wilkerlucio** [comment]
@breandan I'm trying to `3.3.2` as you mentioned, seems to be working fine, just need a few more days to be sure, thanks for the update.

**Comment by rocketraman** [comment]
Perhaps #190 is related too?

**Comment by breandan** [comment]
Closing, as this feature is supported by the JetBrains Plugin Repository. Please report specific bugs in an appropriate ticket. AceJump `3.5.0` partly restores the classic AceJump functionality, and can be enabled by switching the AceJump shortcut under **Settings | Keymap | 🔍 "AceJump"** to **Start in Word Mode**. AceJump `3.5.0` is now available on the plugin repository.
