### ISSUE TITLE
AceJump Disappeared / not working

### ISSUE THREAD

**Issue by LSleutsky** [johnlindquist/AceJump#198]
There was an "update" for AceJump today, and after restarting WebStorm post-completion of update, AceJump is completely disabled - I tried restarting WebStorm (after the initial restart when updates are installed), uninstalling / reinstalling the plugin itself, un-checking and re-checking the plugin box, etc... nothing.

Is anyone else having this issue? Hopefully this will be corrected, as this is a nifty little tool to have...

**Comment by breandan** [comment]
What happened? Could you provide your WebStorm details? (Help | About) Thanks!
