### ISSUE TITLE
Pressing backspace or letter which is not in results breaks it.

### ISSUE THREAD

**Issue by krasa** [johnlindquist/AceJump#20]
for example: results are   A - D,  press H, nothing happens => no more jumping, you have to ESC and try it again.
find something, press backspace, find something else => cannot jump on it

**Comment by breandan** [comment]
Backspace now resets AceJump to the initial state in [AceJump 3.0 Beta](https://github.com/johnlindquist/AceJump/releases/tag/3.0.0), removing any mistypes. Feel free to give it a try and report any issues you encounter. Thanks!
