### ISSUE TITLE
Holding shift on last target character does not highlight text

### ISSUE THREAD

**Issue by ecbrodie** [johnlindquist/AceJump#202]
The following instructions in the README are plain not working for me:

> AceJump tags are not case sensitive. Holding down Shift when typing the last tag character will select all text from the current cursor position to that destination.

I am using RubyMine EE 2017.2.4 and AceJump 3.4.2.

**Comment by ribeiropaulor** [comment]
The same happens here. I'm using PHPStorm 2017.3 (173.3302.10) on Mac Sierra.
