### ISSUE TITLE
If tag drawing proccess interrupted, tag letters persist.

### ISSUE THREAD

**Issue by saroff** [johnlindquist/AceJump#206]
Repro:
1. Press Ace Jump shortcut (ctrl + ; by defalut)
2. Start typing some word
3. Pause a little
4. Then when word is already higlihted but tags are not drawn yet, press esc.
5. If timing was right, tag letters will stay as on screenshot.

Timing is really hard to catch, but i can reproduce it 1 out of 5 times. Try to hit esc right when tags are about to appear.
![image](https://user-images.githubusercontent.com/6500849/34207129-342604e2-e59a-11e7-847e-3b2cd6aa8097.png)

**Comment by breandan** [comment]
Thank you for the detailed report. We recently moved to a threading model, and may have forgotten to clean up reference somewhere. Will investigate.
