### ISSUE TITLE
Feature request: jump to word forward/backwards

### ISSUE THREAD

**Issue by svensp** [johnlindquist/AceJump#210]
Would it be possible to implement jumping akin to `easymotion-w` and `easymotion-b` in AceJump?

What it does is instead of waiting for me to type the prefix of a word it simply tags all words after the cursor(easymotion-w) or before the cursor(easymotion-b)

I use both phpstorm and vim and I got used to jumping around with those commands. I have tried to retrain to use AceJumps prefix jumps but I still can't shake it feeling 'sluggish' in comparison:
`activate acejump` -> `type prefix` -> `wait a noticable moment to switch from prefix to tag selection` -> `type tag`
compared to
`activate easymotion-w or easymotion-b` -> `type tag`

A more generalist approach to this could be to have an AceJump command with configurable predefined prefix and allow escape sequences for special meaning(e.g. `\w` for word jumping) but I rather like the directional component as it keeps the tags short even on a full screen.

**Comment by svensp** [comment]
I tried doing this in the commit above. It seems to work the way I want it except the tags only show up after i press a key.
At first I thought I did something wrong but the same thing happens in the `Display Line Markers` command which already exists. Is this a problem with the current master code?

**Comment by breandan** [comment]
Hey @svensp, this is a great idea! Just had a chance to read your proposal, can you submit this as a PR? I'll try to include this in the next release. Thanks! Related: #204, #201, #114

**Comment by svensp** [comment]
Submitted as #214 but I still have not found a way around the hints only showing up after the first key is pressed

**Comment by breandan** [comment]
Released in AceJump `3.5.0`. Thanks for the idea!
