### ISSUE TITLE
Tag letters persist and AceJump not responds if "Display line markers" shortcut interrupted.

### ISSUE THREAD

**Issue by saroff** [johnlindquist/AceJump#213]
Steps to reproduce:
1. Open relatively large file (I can consistently reproduce it on 512 lines json file)
2. Scroll down to some place in a file and press `Display line markers` shortcut, `ctrl+shift+;` by default.
3. Then immediately press `Esc`.

IDE will become unresponsive for a few seconds, then tag letters will appear as on screenshot. Afterwards, IDE works as normal, but tag letters can't be removed, and Ace Jump don't respond to any shortcuts.

https://i.imgur.com/bNH3SCP.png

IntelliJ IDEA 2017.3.4 (Ultimate Edition)
Build #IU-173.4548.28, built on January 30, 2018

JRE: 1.8.0_152-release-1024-b11 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by saroff** [comment]
Also, this mode is *very* slow. After i encountered this bug, i noticed, that whole file to the point where my screen was, when i pressed `Display line markers`, is tagged. I'm not sure if it is intended.

**Comment by breandan** [comment]
Thanks for the report. This issue should be fixed in the latest release. Can you still reproduce?

**Comment by breandan** [comment]
I'm having trouble reproducing this - tried <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>;</kbd> on a file with thousands of lines and encountered no noticeable latency. Are you using version `3.4.3+`?

**Comment by saroff** [comment]
Yep, looks like i was using 3.4.2. After update this trouble is gone. Sorry for inconvenience.

**Comment by breandan** [comment]
No worries! Thanks for the bug report!
