### ISSUE TITLE
Limit AceJump results to text on the screen?

### ISSUE THREAD

**Issue by terheyden** [johnlindquist/AceJump#236]
Hi, I love this plugin! But I noticed that AceJump markers get created even for text that's not currently visible. Is there a way to have AceJump only consider text on-screen? Thanks.

**Comment by breandan** [comment]
Hi @terheyden, appreciate your feedback! This behavior is intentional and is a duplicate #209. Is there any particular reason why you do not want tags off-screen to be visible? If you are concerned about latency issues when using AceJump on large files, please see #217. Thanks!

**Comment by terheyden** [comment]
BTW the "keep typing" feature is an awesome workaround for this.
