### ISSUE TITLE
Use existing digraphs in text where possible

### ISSUE THREAD

**Issue by sublimator** [johnlindquist/AceJump#27]
It'd be nicer if could use existing digraphs in the words where possible, falling back to random digraphs only when needed. It breaks up the flow.
![hotspots2](https://f.cloud.github.com/assets/525211/295030/69ed9f70-9443-11e2-9137-9e9c19670d91.gif)

That gif's from a pretty old implementation of a sublime text 1 plugin I wrote, but you should be able to understand what I mean.

In my latest implementation [ñonç]ontiguous d[ígrá]phs are used (using non ascii chars here to indicate what is typically underlined, and brackets for the region outlining, as per gif above)

Due to sublime not having an overlay API, I am also using multiple colors for indicating digraph start points. Dunno if that'd be `worth it` considering intelliJ offers labels.

Dig your angular tutes btw. Really good complement to the docs :)

**Comment by breandan** [comment]
This seems like a good idea at first, but after implementing a prototype I'm not convinced this works well in practice. Here are a list of reasons:

1. Not all words will contain a unique substring. 
2. The resulting jump locations are unpredictable.
3. The UI is not compatible with AceJump. (cf. #80)
4. If we share plain text and tags, things start to get really complicated pretty fast. (cf. 8a25a25d938edd73687121472df506937c0b0305).

Closing for now, but feel free to discuss.
