### ISSUE TITLE
Make tags user-configurable

### ISSUE THREAD

**Issue by gregfr** [johnlindquist/AceJump#28]
After watching the nice video about 2.0, I notice that AceJump display on my system is not as clear as on the video:

![image](https://f.cloud.github.com/assets/361582/295329/6bb2e2a6-9480-11e2-96e1-00fd48ab8108.png)

Is there a way to define it to make it clearer?

**Comment by marpe** [comment]
Would be nice if we could configure the colors as well

**Comment by breandan** [comment]
AceJump now has a spiffy new settings page:

<img width="952" alt="screen shot 2017-07-11 at 2 31 43 am" src="https://user-images.githubusercontent.com/175716/28053953-231d79f2-65e1-11e7-8d8b-11b61f9f4d80.png">
