### ISSUE TITLE
Mac OS X 10.8.4: Alt\Option+symbol does not invoke autocomplete popup in PhpStorm 6.0.2

### ISSUE THREAD

**Issue by andreyvolokitin** [johnlindquist/AceJump#32]
I can not get working this feature where you type Alt+symbol and then cursor jumps to desired position with invoking of autocomplete popup.

**Comment by shacharz** [comment]
+1

**Comment by breandan** [comment]
Possibly related to #11, <kbd>Alt</kbd> may have been a old default. AceJump now uses <kbd>Control</kbd>+<kbd>;</kbd>. [AceJump 3.0 Beta](https://github.com/johnlindquist/AceJump/releases/tag/3.0.0) is now out, supporting multi-character search and more highlighting, among other features. Feel free to give it a try and report any feedback you may have! Thanks.
