### ISSUE TITLE
Not working properly on high resolutions

### ISSUE THREAD

**Issue by danpyq** [johnlindquist/AceJump#33]
If i use PHPStorm maximized or in fullscreen with 3 vertical columns on 2560x1440 resolution, the AceJump doesn't work on column no. 3 unless i make it at least 1000px wide. On smaller resolutions everything is ok.

**Comment by Aerondir** [comment]
I've got another manifestation of the same problem, when inspection highlighting underline huge amount of code, like duplicate code warning for  a fresh copy-pasted file, AceJump stops working, only solution is to decrease editor size by splitting pane or opening tools window to decrease screen estate

**Comment by breandan** [comment]
AceJump may indeed become slow or unresponsive when there is a very large amount of text on the screen or the resolution is very high. Working on some different solutions at the moment. Please feel free to report any resolution related issues in this thread.

**Comment by breandan** [comment]
I believe this issue is fixed in recent versions of AceJump. Feel free to reopen if this is not the case.
