### ISSUE TITLE
Immediate word selection with Alt + key is not working anymore (PhpStorm 7.0)

### ISSUE THREAD

**Issue by suamikim** [johnlindquist/AceJump#34]
As stated in the title, the immediate word selection by pressing Alt + key is not working anymore.

Currently I'm working on the newly released PhpStorm 7.0 & AceJump 2.0.5 but I already noticed this some time ago with PhpStorm 6.0.x.

I'd really appreciate if you could fix this and maybe have a look at this other request of mine too (https://github.com/johnlindquist/AceJump/issues/11)!

Thanks & best regards

**Comment by perk11** [comment]
Still doesn't work with PhpStorm 8 on Ubuntu.

**Comment by billizzard** [comment]
Still doesn't work with PHPStorm10

**Comment by breandan** [comment]
@johnlindquist Not sure what "immediate word selection" or the <kbd>Alt</kbd> modifier refers to. Was this superseded by target mode?

**Comment by suamikim** [comment]
Jumping to a word with the <kbd>Alt</kbd> modifier pressed immediately selected the word at the destination position. Comparable to pressing <kbd>Ctrl+W</kbd> inside the editor with the cursor "inside" a word.

I'd really appreciate if you could bring this feature back since I used it a lot.
Also I'm happy to give you more information if needed.

**Comment by breandan** [comment]
@suamikim Thanks for clarifying. I'll make sure we support this feature in the next minor update. In the mean time, you can activate whole-word selection (a.k.a. target mode) by pressing <kbd>Ctrl</kbd>+<kbd>;</kbd> or whatever keystroke is bound to `AceJumpAction` two times in a row, or once before typing the last character to activate (the box should turn red).

**Comment by suamikim** [comment]
Ok, thanks for considering the request!

The `target mode` sounds interesting, unfortunately I can't get it to work. Do I just have to press <kbd>Ctrl+;</kbd> twice or is there anything else to do? If I simply press it twice, nothing noticeable like a color change or a change in behavior happens. I've already tried different variations:
* <kbd>Ctrl+;</kbd> -> <kbd>Ctrl+;</kbd>
* <kbd>Ctrl+;</kbd> -> <kbd>;</kbd>
* <kbd>Ctrl+;</kbd> -> `Enter some text` -> <kbd>Ctrl+;</kbd>

My shortcut is actually <kbd>Ctrl+,</kbd> instead of <kbd>Ctrl+;</kbd> (comma instead of semicolon) since I'm working on a german keyboard where the original <kbd>Ctrl+;</kbd> didn't work at all. Maybe that's the culprit?

**Comment by breandan** [comment]
This issue was resolved in #97. Closing.
