### ISSUE TITLE
Code navigation is not preserved 

### ISSUE THREAD

**Issue by helmus** [johnlindquist/AceJump#35]
When ace jumping multiple times, you can not revisit the places with Code navigation.
( ctrl - alt - left, ctrl - alt -right )

It would be great if this where possible.

**Comment by cvmocanu** [comment]
+1

I am using Ctrl+Alt+Left / Ctrl+Alt+Right a lot.
Having AceJump work with it would make the plugin even more awesome.

**Comment by kwpeters** [comment]
+1

Intergration with `Navigate Back` and `Navigate Forward` would make using AceJump sooooo much more valuable.

**Comment by breandan** [comment]
This feature is now available as of [AceJump 3.2.0](https://plugins.jetbrains.com/idea/plugin/7086-acejump/32936-update). Feel free to report any issues in another ticket.

**Comment by cvmocanu** [comment]
Thanks a lot, this is great news

**Comment by kwpeters** [comment]
Thank you!  Love it!
