### ISSUE TITLE
easymotion 

### ISSUE THREAD

**Issue by terraqout** [johnlindquist/AceJump#48]
Is any way to implement something like that? https://github.com/Lokaltog/vim-easymotion

**Comment by dhanifudin** [comment]
if you use ideavim, you can add map to ~/.ideavimrc like this
```vim
nnoremap s :action AceJumpAction<cr>
```

**Comment by edasaki** [comment]
For posterity (this comes up on google when searching for easymotion for ideavim), the correct mapping is now:

`nnoremap s :action AceAction<CR>`
