### ISSUE TITLE
Start in line mode

### ISSUE THREAD

**Issue by madhat2r** [johnlindquist/AceJump#49]
@johnlindquist 

It would be awesome to be able to specifically start in a mode via a keystroke. I am coming from evil-emacs and it's "ace-jump" implementation allows you to start in the desired mode via a keybinding. 

I am very used to using the jump to line feature. I would like to be able to start AceJump in that mode (or the beginning of line mode) via a keymap. Is this possible now?

**Comment by suamikim** [comment]
Is there even a `jump to line` mode available in the current version of the plugin (`3.0.0`)?
If so, how can I "activate" it?

I just started [this issue](https://github.com/johnlindquist/AceJump/issues/96) which seems slightly related...

**Comment by breandan** [comment]
Jump to first and last characters of a line is available via the <kbd>←</kbd> and <kbd>→</kbd> keys. Start of line is available via <kbd>↑</kbd> key. Will add aliases for <kbd>Home</kbd> and <kbd>End</kbd> in the next minor update. Thanks for the feedback!

**Comment by suamikim** [comment]
Thanks for clearing that up! The arrow keys also work correctly on my german keyboard.

**Comment by breandan** [comment]
This now works by pressing the `AceLineAction` shortcut, which is bound to <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>;</kbd> by default.
