### ISSUE TITLE
No focus in small window =(

### ISSUE THREAD

**Issue by mrArtCore** [johnlindquist/AceJump#56]
Hi there ! 
I regret to say that small window not active when pressed "ctrll + ;" I have to use mouse for activate it =( 
All like in this issue -> https://github.com/johnlindquist/AceJump/issues/41
Android Studio 1.5.1, Ubuntu 14.04

**Comment by iamfreee** [comment]
Arch linux, Phpstorm 10. 

Same problem.

**Comment by breandan** [comment]
Closing as duplicate of #53. Please see the [most recent update](https://github.com/johnlindquist/AceJump/issues/53#issuecomment-197686309).
