### ISSUE TITLE
Highlight text for multi character targets

### ISSUE THREAD

**Issue by eliasbagley** [johnlindquist/AceJump#57]
Hey - 

Let's say I use a common target, like 'e'. On a large screenful a text, there will be many jump targets that then popup, some of them multidigit, such as 'YR'. As soon as the user types the first 'Y', would it be possible to highlight that Y, and hide all jump targets that don't start with 'Y'?

If this seems like a possibility, I'd be willing to take a stab at it and submit an initial PR.

**Comment by breandan** [comment]
Great idea! This feature is now implemented in [AceJump 3.0 Beta](https://github.com/johnlindquist/AceJump/releases/tag/3.0.0). Feel free to give it a try and send your feedback. Thanks.
