### ISSUE TITLE
Getting PluginException after most recent update

### ISSUE THREAD

**Issue by zweicoder** [johnlindquist/AceJump#59]
I'm on Intellij 15.0.1. Extension was working fine before then I updated and now it throws this error every time I input the character I want to jump to:
`10:35:54 PM PluginException: com/maddyhome/idea/vim/helper/EditorHelper : Unsupported major.minor version 52.0 [Plugin: AceJump]`

**Comment by sublimino** [comment]
Same for me on 15.0.4

`Linux <.> 4.2.0-1-amd64 #1 SMP Debian 4.2.6-1 (2015-11-10) x86_64 GNU/Linux`
