### ISSUE TITLE
No shortcuts work

### ISSUE THREAD

**Issue by gregfr** [johnlindquist/AceJump#60]
Greetings
I've reinstalled Acejump in PHPStorm 10 because I've seen the "focus" bug has been fixed.
Indeed it is fixed for me, but all shortcuts are gone: jumping to a letter works, but everything else (up, down, left, right, target mode...) doesn't do anything...
Am I missing something?
Thanks

**Comment by breandan** [comment]
There are a few outstanding reports on PHPStorm. I think they may be related: #67, #34. Will investigate, thanks.
