### ISSUE TITLE
Jump to beginning and end of line stopped work after upgrading to v2.0.9

### ISSUE THREAD

**Issue by anglee** [johnlindquist/AceJump#63]
It use to be, on a Mac, I can initiate AceJump and then `Home` or `End` to jump to the beginning or end of the line, after I upgrade to the new version yesterday, I found this stopped working.

**Comment by anglee** [comment]
Actually I just realized this is likely to be a duplicate of #60, none of the short cut works other than the basic jump to letters.

**Comment by anglee** [comment]
Found the same issue happens with v2.0.7 too. Before this is fixed, I've gone back to use v2.0.5 (downloaded from https://plugins.jetbrains.com/plugin/7086) which seems to work fine with webstorm 11.

**Comment by breandan** [comment]
This should be fixed in AceJump v2.0.13. There was [a regression](https://github.com/johnlindquist/AceJump/commit/cc3a23a3bd6754d11100f15f3dddc4d8529926df#diff-a483c757116bde46e566a8b01520a807L51) that quietly broke this feature. Apologies for the inconvenience.
