### ISSUE TITLE
Writes at selected text, instead of cursor position

### ISSUE THREAD

**Issue by haisi** [johnlindquist/AceJump#64]
IntelliJ IDEA: v15.0.6
Acejump: v2.0.9

If you have text selected and then use acejump, the cursor moves correctly, but when you write new text it's written at the beginning of the selected area, instead of where the cursor was.

Example:
1. On line 91 ```status``` is selected
2. Use acejump to jump to line 86
![step_1](https://cloud.githubusercontent.com/assets/5666773/15214032/f942c8ba-184a-11e6-8347-12898e916380.png)
3. Start typing the character ```t```
![step_2](https://cloud.githubusercontent.com/assets/5666773/15214035/fb60e4e2-184a-11e6-822c-bdead011f0c6.png)

The new character was put in the wrong place (line 91 instead of 86)!

**Comment by breandan** [comment]
Duplicates #9, closing.
