### ISSUE TITLE
Version limit not set correctly for IDEA 2016.2 and above

### ISSUE THREAD

**Issue by rocketraman** [johnlindquist/AceJump#65]
When attempting to install the plugin on a newer version of IntelliJ, such as the 2016.1 EAP (version 162.74.16), version 2.0.5 of the plugin is offered as the latest version, rather than 2.0.9.

I guess because 2.0.5 has a compatible build of `117.117 +` whereas 2.0.9 has a specific range that does not include 162.x.

**Comment by IgnusG** [comment]
It works fine on IntelliJ IDEA 2016.2 EAP Build #IU-162.426.1
(Tried by removing version limit and rebuilding)

**Comment by rocketraman** [comment]
This is even more important now that 2016.2 has been released...
