### ISSUE TITLE
Cannot type text to search in the popup

### ISSUE THREAD

**Issue by jifeon** [johnlindquist/AceJump#67]
OS X 10.11.4
PhpStorm 2016.1.1
Build #PS-145.970, built on May 3, 2016
JRE: 1.8.0_76-release-b162 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

I press `cmd + ;`, see ![](https://i.imgur.com/uYEUF9T.png), then I start typing but nothing happens. Any ideas what am I doing wrong?

**Comment by breandan** [comment]
Could not reproduce. Are you using any other plugins? Please try updating to [AceJump 3.0 Beta](https://github.com/johnlindquist/AceJump/releases/tag/3.0.0) and report if this behavior persists? Thanks.

**Comment by jifeon** [comment]
Just re-checked, it works now, maybe after one regular IDE update. Thx!

**Comment by breandan** [comment]
Good to hear, thanks!
