### ISSUE TITLE
start of work is too long

### ISSUE THREAD

**Issue by sergeychibunin** [johnlindquist/AceJump#69]
Hello! Cool plugin!
But when I am press CTRL+; I waiting some second while little window is shown. In this case meaning of usage this plugin is lost. Can you boost up this plugin?

**Comment by breandan** [comment]
AceJump could definitely use some attention in this department. A good place to start would be refactoring [AceJumpAction](https://github.com/johnlindquist/AceJump/blob/master/src/main/kotlin/com/johnlindquist/acejump/AceJumpAction.kt) which does a bunch of redundant work after each invocation (cf. [configureSearchBox()](https://github.com/johnlindquist/AceJump/blob/master/src/main/kotlin/com/johnlindquist/acejump/AceJumpAction.kt#L125)). I suspect this may affecting performance, need to profile with YourKit for a better picture.

**Comment by sergeychibunin** [comment]
Can I help you, but I do not known Java?

**Comment by breandan** [comment]
Closing this ticket, as we have made significant speed improvements in recent versions. If latency issues persist, feel free to reopen. Thanks @sergeychibunin.
