### ISSUE TITLE
Can't type in more than one character

### ISSUE THREAD

**Issue by jgangso** [johnlindquist/AceJump#75]
Hi,
I'm wondering if I'm missing something. I'm using AceJump with PhpStorm 2016.2 on Ubuntu 14.04(LTS).

When I hit Ctrl + , (custom hotkey) the AceJump text field appears.
I type in one character, and immediately the search results appear on the text file. Now if I typed 'a', there are probably 300 occurences, so basically whatever character I type next, will take me to one the results. :smiley: 

Is there a setting to increase the amount of chars to, say, three before suggestions appear, or am I missing something else ? I see there have been issues with the field focus on Ubuntu, and this might be remotely related..perhaps..?

Thanks for a otherwise great plugin!

**Comment by breandan** [comment]
Yep, it sounds like what you're describing is the intended plugin behavior. The plugin only understands single character jumps - after that it listens for a tag. Is there a conflict in the tagging results (ie. "Z" and "ZA" are both visible?) - if so, this is not supposed to happen. Otherwise, I have something in mind that should make this behavior a little more flexible, but it's going to take a little while to implement.

**Comment by jgangso** [comment]
Thanks. Now I realised the usage a bit better and after that it makes sense. As far as I can see, there are no conflicts between the tagging results.

Br,
Johannes

Lähettäjä: breandan [mailto:notifications@github.com]
Lähetetty: lauantaina 30. heinäkuuta 2016 3.24
Vastaanottaja: johnlindquist/AceJump <AceJump@noreply.github.com>
Kopio: Johannes Gangsö <johannes@aikadesign.fi>; Author <author@noreply.github.com>
Aihe: Re: [johnlindquist/AceJump] Can't type in more than one character (#75)


Yep, it sounds like what you're describing is the intended plugin behavior. The plugin only understands single character jumps - after that it listens for a tag. Is there a conflict in the tagging results (ie. "Z" and "ZA" are both visible?) - if so, this is not supposed to happen. Otherwise, I have something in mind that should make this behavior a little more flexible, but it's going to take a little while to implement.

**Comment by breandan** [comment]
Glad to hear, thanks for submitting feedback. Feel free to submit another ticket if you run into issues.
