### ISSUE TITLE
ideavim command for example "c" in normal mode not working with acejump selection 

### ISSUE THREAD

**Issue by staekblw** [johnlindquist/AceJump#76]
Thanks for this great tool.

I use acejump selection with the SHIFT key, after the selection, I want to use idea vim command c to delete the selection, however it not delete the whole selection.

**Comment by mickaelperrin** [comment]
Indeed, it would be good that when using SHIFT key it will automatically make the selection available in vim.

However, you can use a workaround and switch to visual mode by hitting `v` before launching `AceJump`.

**Comment by breandan** [comment]
Thanks for the feedback! I'll try to see if there is a way to expose text selection to IdeaVim. Right now we are using `editor.selectionModel.setSelection(editor.caretModel.offset, toOffset)` to update the caret selection model. @vlasovskikh Could you clarify if there is a better way to integrate with IdeaVim's selection model? (cf. [AceJumper.kt](https://github.com/johnlindquist/AceJump/blob/master/src/main/kotlin/com/johnlindquist/acejump/keycommands/AceJumper.kt#L30))

**Comment by vlasovskikh** [comment]
@breandan IdeaVim doesn't work directly with IntelliJ's selections. It has to activate its own "visual selection" mode in order to be able to work with them. Right now it doesn't activate this mode on events about setting new selection. I believe fixing https://youtrack.jetbrains.com/issue/VIM-510 and https://youtrack.jetbrains.com/issue/VIM-696 would imply that IdeaVim were able to work with such events.

**Comment by breandan** [comment]
@vlasovskikh Great, thanks for clarifying.

Pausing until further progress is made integrating IdeaVim's selection model with IntelliJ IDEA's selection model. Although it may be possible to deal with IdeaVim directly via an [extension](http://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_extensions_and_extension_points.html) - PRs are always welcome. Please refer to [VIM-510](https://youtrack.jetbrains.com/issue/VIM-510) and [VIM-696](https://youtrack.jetbrains.com/issue/VIM-696) for updates.
