### ISSUE TITLE
whay not to use standard highlighting instead of black covering boxes

### ISSUE THREAD

**Issue by pixsrv** [johnlindquist/AceJump#78]
Hi John
I just found your plugin and the very first thought is why it covers the code (chars) i'm really looking for :)

So maybe your plugin could highlight found occurences with standard highlight (usually yellow I think)
and then present shortcut letters right before and a bit above such yellow highlight.
IMO it would increase already great functionality of the plugin.

br
darth pixel

**Comment by breandan** [comment]
Hello Darth Pixel,

Great idea! This behavior  (or something similar) is planned for the next update. Please stay tuned and thanks for using AceJump!

Best regards,

Breandan

**Comment by breandan** [comment]
Fixed in the latest beta, feel free to give it a try. Thanks!

https://github.com/johnlindquist/AceJump/releases/tag/3.0.0
