### ISSUE TITLE
3. beta should not show hints before I enter input

### ISSUE THREAD

**Issue by andresdominguez** [johnlindquist/AceJump#80]
@breandan 

The new acejump shows hints before I enter anything:

Steps:
1. Command ;

Expected
Hints are shown after I enter one character

Actual
Hints are shown randomly

<img width="446" alt="screen shot 2016-10-23 at 1 42 17 pm" src="https://cloud.githubusercontent.com/assets/1692599/19628210/8958df64-9926-11e6-8e41-94748f0a1767.png">

**Comment by breandan** [comment]
Thanks for the feedback! Updated the beta build: https://github.com/johnlindquist/AceJump/releases/tag/3.0.0
