### ISSUE TITLE
3 beta should not show numbers first

### ISSUE THREAD

**Issue by andresdominguez** [johnlindquist/AceJump#81]
@breandan 

I find the numbers to be very far from my fingers. Also I don't exactly know where the numbers are without looking. I would prefer characters for hints before numbers.

Steps:
1. Hit Command ;
2. Enter a character

Expected
The hints should be letter only

Actual
I see a lot of numbers in the hints

<img width="430" alt="screen shot 2016-10-23 at 1 45 23 pm" src="https://cloud.githubusercontent.com/assets/1692599/19628237/45773736-9927-11e6-94f3-395335a224c9.png">

**Comment by breandan** [comment]
Fixed, thanks.

https://github.com/johnlindquist/AceJump/commit/b5282dc60b8e94684490e7c0b57a3b6449a79f3b#diff-8c8d8afbff80da01a66ced2cb48dcc6eL117
