### ISSUE TITLE
3 beta colors difficult to read in Darkula

### ISSUE THREAD

**Issue by andresdominguez** [johnlindquist/AceJump#82]
@breandan 

The new colors are difficult to read in darkula. For example, here it is difficult to distinguish between E and F

<img width="520" alt="screen shot 2016-10-23 at 1 50 04 pm" src="https://cloud.githubusercontent.com/assets/1692599/19628252/9f3d0fa2-9927-11e6-8e58-9d5dbee0cee7.png">

**Comment by breandan** [comment]
Updated beta release with new build: https://github.com/johnlindquist/AceJump/releases/tag/3.0.0

**Comment by andresdominguez** [comment]
Thanks! I'll download the latest and give it another round of testing.
