### ISSUE TITLE
3 beta does not find targets starting with the letter "i"

### ISSUE THREAD

**Issue by andresdominguez** [johnlindquist/AceJump#85]
@breandan
I am unable to jump to text starting with the letter "i". I downloaded the zip file on Oct 26, 2016.

Steps:
1. Press Command + ;
2. Enter the letter i, or enter "import"

Expected
There should be targets for tokens starting with the letter "i"

Actual
No targets are found

<img width="507" alt="screen shot 2016-10-27 at 12 46 29 pm" src="https://cloud.githubusercontent.com/assets/1692599/19776771/74970e14-9c43-11e6-8061-c15bf812227b.png">

Here is some sample TS file:
```typescript
import {Component} from "@angular/core";
import {Http} from "@angular/http";

@Component({
  selector: 'app-contacts',
  template: `
    <p>
This is a contacts component
    </p>
  `,
  styles: []
})
export class ContactsComponent {
  constructor(private http: Http) {
    http.get('http://localhost:4000/people')
      .map(res => res.json())
  }
}
```

**Comment by breandan** [comment]
This issue is now fixed in the [latest release](https://github.com/johnlindquist/AceJump/releases/tag/3.0.0), thanks!
