### ISSUE TITLE
Beta 3 sometimes there is no letter for a target

### ISSUE THREAD

**Issue by andresdominguez** [johnlindquist/AceJump#86]
@breandan 
Sometimes the plugin does not show the letter for a target.

Steps:
1. Command + ;
2. Enter "This"
3. There are 2 targets shown

Expected
There must be a letter on line 9

Actual
Nothing

<img width="511" alt="screen shot 2016-10-27 at 1 14 06 pm" src="https://cloud.githubusercontent.com/assets/1692599/19777740/a2041c30-9c47-11e6-9ddd-c513a62a88e5.png">

Code
```typescript
import {Component} from "@angular/core";
import {Http} from "@angular/http";


@Component({
  selector: 'app-contacts',
  template: `
    <p>
This is a contacts component
    </p>
  `,
  styles: []
})
export class ContactsComponent {
  contacts$;

  constructor(private http: Http) {
    this.contacts$ = http.get('http://localhost:4000/people')
      .map(res => res.json())
  }
}
```

**Comment by breandan** [comment]
Nice catch, updated the [beta distribution](https://github.com/johnlindquist/AceJump/releases/tag/3.0.0). Thanks!
