### ISSUE TITLE
beta 3. Plugin jumps to incorrect location

### ISSUE THREAD

**Issue by andresdominguez** [johnlindquist/AceJump#92]
@breandan 
The plugin is not jumping to the correct location when I press "D". See screenshots

Steps
1. Go to line 42
2. Command + ;
3. enter "this"
4. A target on line 44 appears with the letter D
5. Hit "D"

Expected
Should jump to line 44

Actual
Jumps to line 40 

Before jumping
<img width="632" alt="screen shot 2016-10-31 at 9 18 32 pm" src="https://cloud.githubusercontent.com/assets/1692599/19876838/4a5f08de-9fb0-11e6-9198-68f8023351ba.png">

After jumping
<img width="276" alt="screen shot 2016-10-31 at 9 18 47 pm" src="https://cloud.githubusercontent.com/assets/1692599/19876842/4f73308e-9fb0-11e6-87d3-fbabb4a45267.png">

Code:
```typescript
import {Component} from '@angular/core';
import {Observable, Subject} from 'rxjs';
import 'rxjs/add/observable/interval';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/merge';
import 'rxjs/add/operator/startWith';
import 'rxjs/add/operator/scan';
import 'rxjs/add/operator/mapTo';
import {Store} from "@ngrx/store";
import {HOUR, SECOND, ADVANCE} from "./reducers";

@Component({
  selector: 'app-root',
  template: `
<input #inputNum type="number" value="0">
<button (click)="click$.next(inputNum.value)">Update</button>
<clock [time]="time | async"></clock>
<div
  (click)="person$.next(person)"
  *ngFor="let person of people | async">
  {{person.name}} is in {{person.time | date:'jms'}}
</div>
`
})
export class AppComponent {
  click$ = new Subject()
    .map((value: string) => ({type: HOUR, payload: parseInt(value)}));

  person$ = new Subject()
    .map((value) => ({payload: value, type: ADVANCE}));

  second$ = Observable.interval(1000)
    .mapTo({type: SECOND, payload: 1});

  time;
  people;

  constructor(store: Store<any>) {
    this.time = store.select('clock');
    this.people = store.select('people');

    Observable
      .merge(
        this.click$, this.second$, this.person$,)
      .subscribe(store.dispatch.bind(store));
  }
}
```

**Comment by breandan** [comment]
This should be fixed in the [latest build](https://github.com/johnlindquist/AceJump/releases/download/3.0.0/AceJump-3.0.0.zip). Thanks for reporting!
