### ISSUE TITLE
Activation of target mode is not working as expected

### ISSUE THREAD

**Issue by suamikim** [johnlindquist/AceJump#97]
I can't get the target mode to work. Do I just have to press <kbd>Ctrl+;</kbd> twice or is there anything else to do? If I simply press it twice, nothing noticeable like a color change or a change in behavior happens. I've already tried different variations:
* <kbd>Ctrl+;</kbd> -> <kbd>Ctrl+;</kbd>
* <kbd>Ctrl+;</kbd> -> <kbd>;</kbd>
* <kbd>Ctrl+;</kbd> -> `Enter some text` -> <kbd>Ctrl+;</kbd>

My shortcut is actually <kbd>Ctrl+,</kbd> instead of <kbd>Ctrl+;</kbd> (comma instead of semicolon) since I'm working on a german keyboard where the original <kbd>Ctrl+;</kbd> didn't work at all. Could this be the culprit?

**Comment by breandan** [comment]
This seems to be related to #31, but you said it was working before the update? I'll have a look.

**Comment by breandan** [comment]
Verified that this works as intended on a US English keyboard, as we are [already mapping](https://github.com/johnlindquist/AceJump/blob/master/src/main/kotlin/com/johnlindquist/acejump/ui/SearchBox.kt#L133) <kbd>Home</kbd> and <kbd>End</kbd> to the correct action. Can you run the code in [this Swing application](https://docs.oracle.com/javase/tutorial/uiswing/examples/events/KeyEventDemoProject/src/events/KeyEventDemo.java) and press the keys on your keyboard that correspond to AceJump actions, then paste the results? I need to see the following key codes for your keyboard: 

* <kbd>End</kbd>
* <kbd>Home</kbd>
* <kbd>Ctrl</kbd>+<kbd>;</kbd>
* <kbd>Alt</kbd>/<kbd>⌥</kbd>

**Comment by suamikim** [comment]
I can't execute the mentioned swing application. If I simply run `java KeyEventDemo.java` inside my console I get the following error:

`Error: Could not find or load main class KeyEventDemo.java`

**Comment by breandan** [comment]
No worries, I think the current solution is flexible enough. If you repeat whichever keystroke is bound to AceJump before completing the jump, it will switch to target mode (all three scenarios from https://github.com/johnlindquist/AceJump/issues/97#issue-186801687 should now work).

**Comment by breandan** [comment]
FYI *Target Mode* can not be activated by pressing the shortcut assigned to `AceTargetMode`  (<kbd>Ctrl</kbd>+<kbd>Alt</kbd>+<kbd>;</kbd> by default) as of [AceJump 3.1.5](https://plugins.jetbrains.com/plugin/download?pr=idea&updateId=31535). I have updated [the instructions](https://github.com/johnlindquist/AceJump#acejump) to reflect this change.
