### ISSUE TITLE
Take line spacing into account

### ISSUE THREAD

**Issue by pix2D** [johnlindquist/AceJump#98]
Preferences > Editor > Colors & Fonts > Font :: When the font line spacing is set to 1 everything displays perfectly. If it's set to something higher (for example 1.5) then everything (AceJump related) seems to display in a offset preserving the 1 line height.

Let me know if you need a screenshot. I'm on macOS (in case it matters). AceJump v3.0.2.

**Comment by breandan** [comment]
Yeah, that looks awful. I'll fix this in the next update, thanks!

**Comment by breandan** [comment]
Line spacing greater than 1.0 also results in a [reproducible glitch](https://twitter.com/lmichailian/status/828200663901409281) where tags appear to slide all over the screen. Investigating.

**Comment by breandan** [comment]
Help post for (future reference)[https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000255130-How-do-I-get-the-highest-point-of-a-caret-located-at-an-offset-]. Thanks @JB-Dmitry!

**Comment by ksdev-pl** [comment]
Thank you for the fix, it looks great now!

**Comment by pix2D** [comment]
@breandan In 3.4.0 things look off again. It was perfect in the previous version.

**Comment by breandan** [comment]
Could you submit a screenshot? Here is what my tags look like on 3.4.0. 
![screen shot 2017-07-23 at 5 46 42 am](https://user-images.githubusercontent.com/175716/28498391-578c77dc-6f6a-11e7-9808-513527c4fa4a.png)
Try varying the line spacing and attach a few screenshots. Thanks!
